### ISSUE TITLE
Heroku app crashes due to MongooseError

### ISSUE THREAD

**Issue by mhalitk** [open-template-hub/auth-server-nodejs-template#144]
<p align="center"><a href="https://opentemplatehub.com"><img src="https://raw.githubusercontent.com/open-template-hub/open-template-hub.github.io/master/assets/logo/brand-logo-broken.png" alt="Logo" width=150></a></p>
<h2 align="center">Open Template Hub - Bug Report</h2>

## Description

I wanted to try auth-server-template. 

1. Using the "Deploy to HEROKU" link in README.md file, I created my account and application in Heroku
2. Sent a couple random request to my app and got 503
3. Opened application logs on Heroku and *Restarted all dynos*
4. Saw application crashed log right after application started (detailed log below)

## Supplementary Info

```
2023-01-24T03:10:49.019588+00:00 heroku[web.1]: State changed from crashed to starting

2023-01-24T03:10:53.050623+00:00 heroku[web.1]: Starting process with command `npm start`

2023-01-24T03:10:56.008450+00:00 app[web.1]: 

2023-01-24T03:10:56.008478+00:00 app[web.1]: > auth-server-template@5.0.1 start

2023-01-24T03:10:56.008479+00:00 app[web.1]: > node version-generator.ts > ./version.ts && ts-node auth-server.main.ts

2023-01-24T03:10:56.008479+00:00 app[web.1]: 

2023-01-24T03:11:00.384906+00:00 heroku[web.1]: Process exited with status 1

2023-01-24T03:11:00.205906+00:00 app[web.1]: MongoDB Preloaded Successfully.

2023-01-24T03:11:00.217972+00:00 app[web.1]: PostgreSQL Loaded Successfully.

2023-01-24T03:11:00.220479+00:00 app[web.1]: MQ Loaded Successfully.

2023-01-24T03:11:00.223707+00:00 app[web.1]: Auth Server is running on port 7475

2023-01-24T03:11:00.223898+00:00 app[web.1]: Startup Memory Usage: 165.07 MB

2023-01-24T03:11:00.229103+00:00 app[web.1]: /app/node_modules/mongoose/lib/connection.js:695

2023-01-24T03:11:00.229104+00:00 app[web.1]:     throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +

2023-01-24T03:11:00.229104+00:00 app[web.1]:           ^

2023-01-24T03:11:00.230249+00:00 app[web.1]: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

2023-01-24T03:11:00.230249+00:00 app[web.1]:     at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:695:11)

2023-01-24T03:11:00.230250+00:00 app[web.1]:     at Mongoose.createConnection (/app/node_modules/mongoose/lib/index.js:351:10)

2023-01-24T03:11:00.230250+00:00 app[web.1]:     at /app/node_modules/@open-template-hub/common/lib/provider/mongo.provider.ts:35:34

2023-01-24T03:11:00.230251+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-01-24T03:11:00.436511+00:00 heroku[web.1]: State changed from starting to crashed
```

<table align="right"><tr><td><a href="https://opentemplatehub.com"><img src="https://raw.githubusercontent.com/open-template-hub/open-template-hub.github.io/master/assets/logo/brand-logo.png" width="50px" alt="oth"/></a></td><td><b>Open Template Hub © 2023</b></td></tr></table>

**Comment by mhalitk** [comment]
Following the error and readme, I figured this is my mistake, I need to create environment variables as well. Now I created a MongoDB account and provided the variable using config vars in Heroku.

More errors follow though, I know due to my configuration. Not working with MongoDB, PostgreSQL etc. before it's not super clear if I have to provide all environment variables in readme.md. Is there a sample configuration I can look at? or more documentation?
